export default defineAppConfig({
  identity: {
    i18nKey: "portfolioData.identity",
    available: true,
  },

  links: {
    github: "https://github.com/Djam18",
    linkedin: "https://linkedin.com/in/abdel-djamal-adam-b952381b2",
    cal: "https://cal.com/ton-compte",
    whatsapp: "https://wa.me/22966646310",
    email: "adamdjamal18@gmail.com",
  },

  education: [
    {
      i18nKey: "portfolioData.education.smartel",
      skills: ["Laravel", "Nuxt.js", "Vue.js", "TypeScript"],
    },
    {
      i18nKey: "portfolioData.education.eneam",
      skills: ["PHP", "SQL", "Algorithmique", "Systèmes d'information"],
    },
  ],

  certifications: [
    {
      i18nKey: "portfolioData.certifications.aiFluency",
      issuer: "Anthropic",
      credentialId: "thnjbp4m5s5n",
      expired: false,
      skills: ["AI", "Prompt Engineering"],
      url: "https://www.linkedin.com/in/abdel-djamal-adam-b952381b2/overlay/Certifications/1074494503/treasury/",
    },
    {
      i18nKey: "portfolioData.certifications.claudeCode101",
      issuer: "Anthropic",
      credentialId: "c4wwij2se4cs",
      expired: false,
      skills: ["Claude Code", "AI Coding Agents"],
      url: "https://www.linkedin.com/in/abdel-djamal-adam-b952381b2/overlay/Certifications/1074494503/treasury/",
    },
    {
      i18nKey: "portfolioData.certifications.claudeCodeInAction",
      issuer: "Anthropic",
      credentialId: "o5qsz8yqtxf6",
      expired: false,
      skills: ["Claude Code", "MCP Servers", "GitHub Integration"],
      url: "https://www.linkedin.com/in/abdel-djamal-adam-b952381b2/overlay/Certifications/1074494503/treasury/",
    },
    {
      i18nKey: "portfolioData.certifications.googleDigital",
      issuer: "Udemy",
      credentialId: "UC-90ef65f8-978f-41e4-a08e-f55702473349",
      expired: true,
      skills: ["Google Analytics", "Google Ads", "SEO"],
      url: "",
    },
    {
      i18nKey: "portfolioData.certifications.chatgptMidjourney",
      issuer: "Udemy",
      credentialId: "UC-a11912c2-e361-4157-ab68-d5a34dd2e741",
      expired: true,
      skills: ["Prompt Engineering", "Midjourney"],
      url: "",
    },
    {
      i18nKey: "portfolioData.certifications.formationWeb",
      issuer: "Udemy",
      credentialId: "UC-e7a70b35-6a04-43be-a90d-a7f32f28dbbc",
      expired: true,
      skills: ["Bootstrap", "PHP"],
      url: "",
    },
  ],

  skills: {
    frontend: [
      { name: "Vue.js / Nuxt", icon: "logos:vue", level: "expert", project: "ats-analyzer" },
      {
        name: "TypeScript",
        icon: "logos:typescript-icon",
        level: "proficient",
      },
      { name: "Tailwind CSS", icon: "logos:tailwindcss-icon", level: "expert" },
      {
        name: "React / React Native",
        icon: "logos:react",
        level: "proficient",
      },
      { name: "JavaScript", icon: "logos:javascript", level: "expert" },
      { name: "HTML / CSS", icon: "logos:html-5", level: "expert" },
    ],
    backend: [
      { name: "Laravel / PHP", icon: "logos:laravel", level: "expert", project: "shop-tenant" },
      { name: "Node.js", icon: "logos:nodejs-icon", level: "proficient" },
      { name: "Express.js", icon: "logos:express", level: "proficient" },
      { name: "REST APIs", icon: "ph:cloud-arrow-up", level: "expert" },
      { name: "Python", icon: "logos:python", level: "familiar", project: "operia" },
    ],
    database: [
      {
        name: "PostgreSQL",
        icon: "logos:postgresql",
        level: "proficient",
        project: "shop-tenant",
      },
      { name: "MongoDB", icon: "logos:mongodb-icon", level: "proficient" },
      { name: "Supabase", icon: "logos:supabase-icon", level: "proficient", project: "ats-analyzer" },
      { name: "MySQL", icon: "logos:mysql-icon", level: "familiar" },
    ],
    devops: [
      { name: "Git / GitHub", icon: "logos:github-icon", level: "expert" },
      {
        name: "Docker",
        icon: "logos:docker-icon",
        level: "familiar",
        project: "shop-tenant",
      },
      { name: "Vercel", icon: "logos:vercel-icon", level: "proficient" },
      { name: "Linux", icon: "logos:linux-tux", level: "familiar" },
    ],
    ai: [
      {
        name: "Claude Code",
        icon: "ph:robot",
        level: "proficient",
        project: "operia",
      },
      { name: "Prompt Engineering", icon: "ph:brain", level: "proficient", project: "ats-analyzer" },
      { name: "MCP Servers", icon: "ph:plug", level: "familiar", project: "operia" },
    ],
  },

  experience: [
    {
      slug: "infraxdev",
      current: true,
      skills: [
        "Vue.js",
        "Nuxt.js",
        "Laravel",
        "PHP",
        "MongoDB",
        "Pinia",
        "Vuex",
        "Supabase",
        "Mongoose",
        "Vite",
      ],
    },
    {
      slug: "osiGroup",
      current: false,
      skills: [
        "React.js",
        "Express.js",
        "Node.js",
        "PostgreSQL",
        "TailwindCSS",
        "React Hooks",
      ],
    },
    {
      slug: "rintio",
      current: false,
      skills: [
        "Angular",
        "JavaScript",
        "Angular Material",
        "Ionic",
        "Git",
        "Bootstrap",
      ],
    },
  ],

  services: [
    {
      slug: "webApplications",
      icon: "ph:code",
      techs: ["Vue.js / Nuxt", "Laravel", "TypeScript", "Tailwind CSS"],
      project: "ats-analyzer",
    },
    {
      slug: "mobileApps",
      icon: "ph:device-mobile",
      techs: ["React Native", "Expo", "TypeScript", "Mobile UI"],
      project: null,
    },
    {
      slug: "seoPerformance",
      icon: "ph:gauge",
      techs: ["Nuxt SEO", "Lighthouse", "Core Web Vitals", "Web Performance"],
      project: "adam-portfolio",
    },
    {
      slug: "aiAutomation",
      icon: "ph:robot",
      techs: ["Claude Code", "MCP Servers", "Prompt Engineering", "Python"],
      project: "operia",
    },
  ],

  projects: [
    {
      slug: "ats-analyzer",
      i18nKey: "portfolioData.projects.atsAnalyzer",
      year: "2026",
      image: "/images/portfolio/ats-analyzer.png",
      stack: ["Nuxt 4", "Vue 3", "TypeScript", "Supabase", "HuggingFace", "Stripe", "Tailwind CSS"],
      liveUrl: null,
      repoUrl: "https://github.com/Djam18/ats-analyzer",
      category: "ai",
      status: "in-progress",
    },
    {
      slug: "operia",
      i18nKey: "portfolioData.projects.operia",
      year: "2026",
      image: "/images/portfolio/operia.png",
      stack: ["Python", "FastAPI", "Vue 3", "TypeScript", "MCP", "SQLite", "Tailwind CSS", "Playwright"],
      liveUrl: null,
      repoUrl: "https://github.com/Djam18/operia",
      category: "ai",
      status: "in-progress",
    },
    {
      slug: "shop-tenant",
      i18nKey: "portfolioData.projects.shopTenant",
      year: "2026",
      image: null,
      stack: ["Laravel", "Vue.js", "Stripe", "PostgreSQL", "Docker"],
      liveUrl: null,
      repoUrl: "https://github.com/Djam18/shop-tenant",
      category: "backend",
      status: "analysis",
    },
    {
      slug: "adam-portfolio",
      i18nKey: "portfolioData.projects.adamPortfolio",
      year: "2025",
      image: "/images/portfolio/portfolio-v2.jpg",
      stack: ["Vue.js", "Nuxt 4", "TypeScript", "Tailwind CSS", "Nuxt Content", "GSAP"],
      liveUrl: "https://adam-portfolio.vercel.app",
      repoUrl: "https://github.com/Djam18/portfolio",
      category: "frontend",
      status: "live",
    },
  ],
});
