export default defineAppConfig({
  identity: {
    i18nKey: "portfolioData.identity",
    available: true,
  },

  links: {
    github: "https://github.com/Djam18",
    linkedin: "https://linkedin.com/in/abdel-djamal-adam-b952381b2",
    cal: "https://cal.com/ton-compte",
    whatsapp: "https://wa.me/22966646310",
    email: "adamdjamal18@gmail.com",
  },

  education: [
    {
      i18nKey: "portfolioData.education.smartel",
      skills: ["Laravel", "Nuxt.js", "Vue.js", "TypeScript"],
    },
    {
      i18nKey: "portfolioData.education.eneam",
      skills: ["PHP", "SQL", "Algorithmique", "Systèmes d'information"],
    },
  ],

  certifications: [
    {
      i18nKey: "portfolioData.certifications.aiFluency",
      issuer: "Anthropic",
      credentialId: "thnjbp4m5s5n",
      expired: false,
      skills: ["AI", "Prompt Engineering"],
      url: "https://www.linkedin.com/in/abdel-djamal-adam-b952381b2/overlay/Certifications/1074494503/treasury/",
    },
    {
      i18nKey: "portfolioData.certifications.claudeCode101",
      issuer: "Anthropic",
      credentialId: "c4wwij2se4cs",
      expired: false,
      skills: ["Claude Code", "AI Coding Agents"],
      url: "https://www.linkedin.com/in/abdel-djamal-adam-b952381b2/overlay/Certifications/1074494503/treasury/",
    },
    {
      i18nKey: "portfolioData.certifications.claudeCodeInAction",
      issuer: "Anthropic",
      credentialId: "o5qsz8yqtxf6",
      expired: false,
      skills: ["Claude Code", "MCP Servers", "GitHub Integration"],
      url: "https://www.linkedin.com/in/abdel-djamal-adam-b952381b2/overlay/Certifications/1074494503/treasury/",
    },
    {
      i18nKey: "portfolioData.certifications.googleDigital",
      issuer: "Udemy",
      credentialId: "UC-90ef65f8-978f-41e4-a08e-f55702473349",
      expired: true,
      skills: ["Google Analytics", "Google Ads", "SEO"],
      url: "",
    },
    {
      i18nKey: "portfolioData.certifications.chatgptMidjourney",
      issuer: "Udemy",
      credentialId: "UC-a11912c2-e361-4157-ab68-d5a34dd2e741",
      expired: true,
      skills: ["Prompt Engineering", "Midjourney"],
      url: "",
    },
    {
      i18nKey: "portfolioData.certifications.formationWeb",
      issuer: "Udemy",
      credentialId: "UC-e7a70b35-6a04-43be-a90d-a7f32f28dbbc",
      expired: true,
      skills: ["Bootstrap", "PHP"],
      url: "",
    },
  ],

  skills: {
    frontend: [
      { name: "Vue.js / Nuxt", icon: "logos:vue", level: "expert" },
      {
        name: "TypeScript",
        icon: "logos:typescript-icon",
        level: "proficient",
      },
      { name: "Tailwind CSS", icon: "logos:tailwindcss-icon", level: "expert" },
      {
        name: "React / React Native",
        icon: "logos:react",
        level: "proficient",
      },
      { name: "JavaScript", icon: "logos:javascript", level: "expert" },
      { name: "HTML / CSS", icon: "logos:html-5", level: "expert" },
    ],
    backend: [
      { name: "Laravel / PHP", icon: "logos:laravel", level: "expert" },
      { name: "Node.js", icon: "logos:nodejs-icon", level: "proficient" },
      { name: "Express.js", icon: "logos:express", level: "proficient" },
      { name: "REST APIs", icon: "ph:cloud-arrow-up", level: "expert" },
      { name: "Python", icon: "logos:python", level: "familiar" },
    ],
    database: [
      {
        name: "PostgreSQL",
        icon: "logos:postgresql",
        level: "proficient",
        project: "query-craft",
      },
      { name: "MongoDB", icon: "logos:mongodb-icon", level: "proficient" },
      { name: "Supabase", icon: "logos:supabase-icon", level: "proficient" },
      { name: "MySQL", icon: "logos:mysql-icon", level: "familiar" },
    ],
    devops: [
      { name: "Git / GitHub", icon: "logos:github-icon", level: "expert" },
      {
        name: "Docker",
        icon: "logos:docker-icon",
        level: "familiar",
        project: "deploy-lab",
      },
      { name: "Vercel", icon: "logos:vercel-icon", level: "proficient" },
      { name: "Linux", icon: "logos:linux-tux", level: "familiar" },
    ],
    ai: [
      {
        name: "Claude Code",
        icon: "ph:robot",
        level: "proficient",
        project: "ai-blog-autopilot",
      },
      { name: "Prompt Engineering", icon: "ph:brain", level: "proficient" },
      { name: "MCP Servers", icon: "ph:plug", level: "familiar" },
    ],
  },

  experience: [
    {
      slug: "infraxdev",
      current: true,
      skills: ["Vue.js", "Nuxt.js", "Laravel", "PHP", "MongoDB", "Pinia", "Vuex", "Supabase", "Mongoose", "Vite"],
    },
    {
      slug: "osiGroup",
      current: false,
      skills: ["React.js", "Express.js", "Node.js", "PostgreSQL", "TailwindCSS", "React Hooks"],
    },
    {
      slug: "rintio",
      current: false,
      skills: ["Angular", "JavaScript", "Angular Material", "Ionic", "Git", "Bootstrap"],
    },
  ],

  projects: [
    {
      slug: "adam-portfolio",
      i18nKey: "portfolioData.projects.adamPortfolio",
      year: "2025",
      image: "/images/portfolio/portfolio-v2.jpg",
      stack: ["Vue.js", "Nuxt 4", "TypeScript", "Tailwind", "GitHub Actions"],
      liveUrl: "https://adam.codes",
      repoUrl: "https://github.com/adam/portfolio",
      category: "frontend",
    },
    {
      slug: "saas-ecommerce",
      i18nKey: "portfolioData.projects.saasEcommerce",
      year: "2025",
      image: "/images/portfolio/saas.jpg",
      stack: ["Laravel", "Vue.js", "Stripe", "PostgreSQL", "Docker"],
      liveUrl: "https://saas.app",
      repoUrl: null,
      category: "backend",
    },
    {
      slug: "mobile-x",
      i18nKey: "portfolioData.projects.mobileX",
      year: "2024",
      image: "/images/portfolio/mobile-x.jpg",
      stack: ["React Native", "Expo", "Node.js", "MongoDB"],
      liveUrl: null,
      repoUrl: "https://github.com/adam/mobile-x",
      category: "frontend",
    },
    {
      slug: "query-craft",
      i18nKey: "portfolioData.projects.queryCraft",
      year: "2026",
      image: "/images/portfolio/query-craft.jpg",
      stack: ["Vue.js", "Node.js", "PostgreSQL", "Docker", "Tailwind"],
      liveUrl: "https://query-craft.vercel.app",
      repoUrl: "https://github.com/your-username/query-craft",
      category: "database",
    },
    {
      slug: "deploy-lab",
      i18nKey: "portfolioData.projects.deployLab",
      year: "2025",
      image: "/images/portfolio/deploy-lab.jpg",
      stack: ["Docker", "GitHub Actions", "Vercel", "Nginx", "Linux"],
      liveUrl: "https://deploy-lab.vercel.app",
      repoUrl: "https://github.com/your-username/deploy-lab",
      category: "devops",
    },
    {
      slug: "ai-blog-autopilot",
      i18nKey: "portfolioData.projects.aiBlogAutopilot",
      year: "2026",
      image: "/images/portfolio/ai-autopilot.jpg",
      stack: [
        "Nuxt 4",
        "Claude API",
        "Prompt Engineering",
        "Supabase",
        "Figma",
      ],
      liveUrl: "https://ai-autopilot.vercel.app",
      repoUrl: "https://github.com/your-username/ai-blog-autopilot",
      category: "ai",
    },
  ],
});